- name: Delete user
  include_tasks: delete_user.yaml

- name: Create user 
  ansible.builtin.uri:
    url: "{{ server_url }}/api-internal/users/" 
    method: POST
    headers:
      Authorization: "{{ dast_token }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ new_user_data }}"
    validate_certs: no
    status_code: 201
  register: create_user_response
  no_log: false

# For auditing - it will be better to use dedicated user to install extensions.
# Therefeore we create new user and get a token which is then used to install extensions.
- name: Extract Concourse token
  set_fact:
    concourse_token: "{{ create_user_response.json.secret }}"
  when: create_user_response is defined and create_user_response is not skipped
    
